# Copyright (c) 2026 by pingod. All Rights Reserved.
# AirPlay audio (RAOP) for Macast, by supervising shairport-sync
#
# Macast Metadata
# <macast.title>AirPlay Audio (RAOP)</macast.title>
# <macast.protocol>AirPlayAudioProtocol</macast.protocol>
# <macast.platform>darwin,linux</macast.platform>
# <macast.version>0.2</macast.version>
# <macast.host_version>0.7</macast.host_version>
# <macast.author>pingod</macast.author>
# <macast.desc>Receive AirPlay audio from an iPhone / iPad / Mac and play it on this machine's speakers. Macast itself only implements the video half of AirPlay; this plugin supervises shairport-sync, which you install yourself.</macast.desc>
#
# Why a supervisor and not an implementation: RAOP audio is a real protocol
# (RSA key exchange, ALAC over UDP, AES) and re-implementing it in a single-file
# plugin would be a project, not a feature. shairport-sync already does it, is
# packaged on macOS and Linux, does its own mDNS advertising, and picks the
# audio device up from the system. So Macast's job is the part shairport-sync
# does not do for you: start it with a config that carries your Macast name,
# keep it alive with the plugin's own lifecycle, and tell you whether it is
# running.
#
# Notes for whoever touches this next:
#   * the generated config is deliberately minimal (`general = { name = ... }`).
#     Output backend, mixer and port are compile-time or system decisions on the
#     user's machine; guessing them here would break setups that already work.
#   * state is *not* reported as DLNA transport state. There is no media URL in
#     RAOP, and claiming PLAYING would contradict the ledger DLNA maintains for
#     the other protocols. Connection and disconnection are surfaced as
#     notifications instead.
#   * `uses_ssdp = False`: nothing here is discovered over SSDP, and setting it
#     true would keep the SSDP server alive when RAOP is the only protocol on.
#     shairport-sync advertises over mDNS itself.

import os
import shutil
import subprocess
import threading
import logging
from enum import Enum

import cherrypy

from macast import utils, notice
from macast.protocol import Protocol
from macast.utils import Setting

logger = logging.getLogger("AirPlayAudio")
logger.setLevel(logging.INFO)

CONFIG_NAME = 'shairport-sync.conf'


def _tell(message):
    """Tell the user twice: once as a notification, once to last.

    The notification is gone in five seconds and the user has to install
    something from it, so the same sentence goes to the message board the
    「电脑投屏」tab reads (`macast/notice.py`) -- and the install command is
    repeated there as an open requirement until shairport-sync turns up.
    """
    notice.record(message)
    cherrypy.engine.publish('app_notify', 'Macast', message)


class SettingProperty(Enum):
    #: Speaker name shown to AirPlay senders. Unset (or empty) means "follow
    #: Macast's DLNA friendly name", which is what v0.1 always did.
    RAOP_Device_Name = 1

#: PATH first, then the usual install spots: a GUI app started from Finder or
#: the Dock does not inherit the shell's PATH.
EXTRA_BIN_DIRS = ('/opt/homebrew/bin', '/usr/local/bin', '/opt/local/bin',
                  '/usr/bin')


def service_name():
    """The name shairport-sync advertises: the plugin's own override when the
    user set one, else Macast's friendly name. `has` before `get` because
    Setting.get() with a default *creates* the key (AGENTS §4.2)."""
    if Setting.has(SettingProperty.RAOP_Device_Name):
        name = str(Setting.get(SettingProperty.RAOP_Device_Name) or '').strip()
        if name:
            return name
    return Setting.get_friendly_name()


def find_shairport():
    """Path of the shairport-sync binary, or None.

    Module-level so tests can swap it, and looked up at start() rather than at
    import: installing shairport-sync while Macast runs should not need a
    restart.
    """
    found = shutil.which('shairport-sync')
    if found:
        return found
    for directory in EXTRA_BIN_DIRS:
        candidate = os.path.join(directory, 'shairport-sync')
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate
    return None


def config_body(name):
    """The generated shairport-sync config, as text.

    Escaped by hand because this is a C-style config: an unescaped quote in the
    device name would end the string early and turn the rest of the user's name
    into a syntax error shairport-sync refuses to start on.
    """
    safe = (name or 'Macast').replace('\\', '\\\\').replace('"', '\\"')
    return (
        '// Generated by Macast\'s "AirPlay Audio (RAOP)" plugin.\n'
        '// The service name comes from Macast\'s friendly-name setting; edit it\n'
        '// there rather than here, or the next start will overwrite this file.\n'
        'general =\n'
        '{\n'
        '    name = "%s";\n'
        '};\n' % safe
    )


def write_config(name):
    """Write the config and return its path."""
    os.makedirs(utils.SETTING_DIR, exist_ok=True)
    path = os.path.join(utils.SETTING_DIR, CONFIG_NAME)
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(config_body(name))
    return path


class AirPlayAudioProtocol(Protocol):
    """Keeps shairport-sync running; Macast never touches the audio itself."""

    #: Nothing to discover over SSDP (shairport-sync advertises over mDNS).
    uses_ssdp = False

    def __init__(self):
        super(AirPlayAudioProtocol, self).__init__()
        self._proc = None
        self._reader = None
        self._lock = threading.Lock()

    def running(self):
        with self._lock:
            return self._proc is not None and self._proc.poll() is None

    def start(self):
        if self.running():
            return
        binary = find_shairport()
        if binary is None:
            message = ('未找到 shairport-sync，AirPlay 音频无法启动：'
                       'brew install shairport-sync（Linux: 包管理器安装）')
            logger.error(message)
            _tell(message)
            notice.requirement(
                'shairport-sync',
                label='AirPlay 音频需要 shairport-sync',
                detail='Macast 只监督它、不实现 RAOP：装上它才能把这台电脑的声音投给 '
                       'AirPlay 音箱。Linux 用发行版的包管理器装同名包。',
                command='brew install shairport-sync')
            return
        notice.satisfied('shairport-sync')
        try:
            config = write_config(service_name())
        except OSError as e:
            message = '无法写入 shairport-sync 配置：{}'.format(e)
            logger.error(message)
            _tell(message)
            return
        # -v so the log carries "Connection from ..." lines; without it
        # shairport-sync says nothing at all and there is no way to tell whether
        # a phone ever reached us.
        argv = [binary, '-v', '-c', config]
        logger.info('starting %s', ' '.join(argv))
        try:
            proc = subprocess.Popen(argv, stdout=subprocess.PIPE,
                                    stderr=subprocess.STDOUT,
                                    stdin=subprocess.DEVNULL,
                                    text=True, bufsize=1)
        except OSError as e:
            message = '启动 shairport-sync 失败：{}'.format(e)
            logger.error(message)
            _tell(message)
            return
        with self._lock:
            self._proc = proc
        self._reader = threading.Thread(target=self._read_output, args=(proc,),
                                        daemon=True, name='RAOP_LOG')
        self._reader.start()

    def stop(self):
        with self._lock:
            proc, self._proc = self._proc, None
        if proc is not None and proc.poll() is None:
            try:
                proc.terminate()
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()
            except OSError as e:
                logger.error('cannot stop shairport-sync: %s', e)
        logger.info('shairport-sync stopped')

    def reload(self):
        self.stop()
        self.start()

    def _read_output(self, proc):
        """Follow shairport-sync's log and surface connections to the user.

        It has no status socket, so the log is the only signal available. This
        deliberately reports *AirPlay* connection events as notifications rather
        than as DLNA transport state: there is no media url in RAOP, and DLNA
        owns the transport ledger for the other protocols.
        """
        try:
            for line in proc.stdout:
                line = line.strip()
                if not line:
                    continue
                logger.info('shairport-sync: %s', line)
                lowered = line.lower()
                if 'connection from' in lowered:
                    _tell('AirPlay 音频已连接')
                elif 'connection closed' in lowered or 'disconnected' in lowered:
                    _tell('AirPlay 音频已断开')
        except (OSError, ValueError) as e:
            logger.error('shairport-sync log reader stopped: %s', e)


if __name__ == '__main__':
    from macast import cli
    from macast_renderer.mpv import MPVRenderer

    cli(renderer=MPVRenderer(path='mpv'), protocol=AirPlayAudioProtocol())
